### ISSUE TITLE
Skill rolls being calculated wrong vs. JSON values

### ISSUE THREAD

**Issue by Thirtybird** [Thirtybird/TTSHeroMod#21]
GM_Champion reports the skill rolls for all their characters are 1 lower than they should be.

https://discord.com/channels/624299158362259502/624299158362259504/1086786189337575495

Brennall says heromod may be calculating these instead of using the JSON provided value

**Comment by GM-Champion** [comment]
I would clarify - the skills are *missing* all levels bought above base - e.g. Traveller Mechanics 2 becomes, for a 10 INT in HERO, Mechanics 13-, bought as 3 points for 11-, and two levels with just that skill. *All* of the levels fail to be included.

**Comment by Thirtybird** [comment]
Fixed in commit a899075
